-- 小羊书吧数据库初始化 SQL
-- 请在 Supabase SQL 编辑器中执行

-- ============================================
-- 书源表 (sources)
-- ============================================
CREATE TABLE IF NOT EXISTS sources (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL UNIQUE,
  url TEXT NOT NULL,
  description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ============================================
-- 小说表 (novels)
-- ============================================
CREATE TABLE IF NOT EXISTS novels (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  author VARCHAR(100),
  description TEXT,
  cover_url TEXT,
  category VARCHAR(50),
  chapters_url TEXT,
  source VARCHAR(100) REFERENCES sources(name),
  status VARCHAR(20) DEFAULT 'unknown',
  word_count INTEGER DEFAULT 0,
  last_updated TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(title, source)
);

-- 创建索引
CREATE INDEX IF NOT EXISTS idx_novels_title ON novels(title);
CREATE INDEX IF NOT EXISTS idx_novels_author ON novels(author);
CREATE INDEX IF NOT EXISTS idx_novels_category ON novels(category);
CREATE INDEX IF NOT EXISTS idx_novels_source ON novels(source);

-- ============================================
-- 章节表 (chapters)
-- ============================================
CREATE TABLE IF NOT EXISTS chapters (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  novel_id BIGINT REFERENCES novels(id) ON DELETE CASCADE,
  title VARCHAR(255) NOT NULL,
  url TEXT NOT NULL,
  chapter_number INTEGER,
  word_count INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(novel_id, chapter_number)
);

CREATE INDEX IF NOT EXISTS idx_chapters_novel_id ON chapters(novel_id);

-- ============================================
-- 内容表 (chapter_content) - 可选，存储全文
-- ============================================
CREATE TABLE IF NOT EXISTS chapter_content (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chapter_id BIGINT REFERENCES chapters(id) ON DELETE CASCADE,
  content TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_chapter_content_chapter_id ON chapter_content(chapter_id);

-- ============================================
-- RLS 策略 (可选)
-- ============================================
-- 启用 RLS
-- ALTER TABLE sources ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE novels ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE chapters ENABLE ROW LEVEL SECURITY;

-- 公开读取策略
-- CREATE POLICY "Public sources" ON sources FOR SELECT USING (true);
-- CREATE POLICY "Public novels" ON novels FOR SELECT USING (true);
-- CREATE POLICY "Public chapters" ON chapters FOR SELECT USING (true);

-- 允许所有操作 (根据需求调整)
-- CREATE POLICY "Allow all sources" ON sources FOR ALL USING (true);
-- CREATE POLICY "Allow all novels" ON novels FOR ALL USING (true);
-- CREATE POLICY "Allow all chapters" ON chapters FOR ALL USING (true);

-- ============================================
-- 插入默认书源
-- ============================================
INSERT INTO sources (name, url, description) VALUES
  ('笔趣阁', 'https://www.xbiquge.so', '经典小说书源，更新快'),
  ('顶点小说', 'https://www.23us.com', '顶点小说网'),
  ('笔趣阁阁', 'https://www.bxwxorg.com', '笔趣阁阁小说网')
ON CONFLICT (name) DO NOTHING;

SELECT '数据库初始化完成!' as message;
