// 创建数据库表的脚本
const { Pool } = require('pg');

const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
  ssl: { rejectUnauthorized: false }
});

const sql = `
-- 书源表 (sources)
CREATE TABLE IF NOT EXISTS sources (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL UNIQUE,
  url TEXT NOT NULL,
  description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 小说表 (novels)
CREATE TABLE IF NOT EXISTS novels (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  author VARCHAR(100),
  description TEXT,
  cover_url TEXT,
  category VARCHAR(50),
  chapters_url TEXT,
  source VARCHAR(100),
  status VARCHAR(20) DEFAULT 'unknown',
  word_count INTEGER DEFAULT 0,
  last_updated TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(title, source)
);

-- 创建索引
CREATE INDEX IF NOT EXISTS idx_novels_title ON novels(title);
CREATE INDEX IF NOT EXISTS idx_novels_author ON novels(author);
CREATE INDEX IF NOT EXISTS idx_novels_category ON novels(category);
CREATE INDEX IF NOT EXISTS idx_novels_source ON novels(source);

-- 章节表 (chapters)
CREATE TABLE IF NOT EXISTS chapters (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  novel_id BIGINT,
  title VARCHAR(255) NOT NULL,
  url TEXT NOT NULL,
  chapter_number INTEGER,
  word_count INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(novel_id, chapter_number)
);

CREATE INDEX IF NOT EXISTS idx_chapters_novel_id ON chapters(novel_id);

-- 内容表 (chapter_content)
CREATE TABLE IF NOT EXISTS chapter_content (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chapter_id BIGINT,
  content TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_chapter_content_chapter_id ON chapter_content(chapter_id);

-- 插入默认书源
INSERT INTO sources (name, url, description) VALUES
  ('笔趣阁', 'https://www.xbiquge.so', '经典小说书源，更新快'),
  ('顶点小说', 'https://www.23us.com', '顶点小说网'),
  ('笔趣阁阁', 'https://www.bxwxorg.com', '笔趣阁阁小说网')
ON CONFLICT (name) DO NOTHING;
`;

async function createTables() {
  // Supabase 连接字符串格式: postgres://postgres:[password]@db.nehhbwuycrujvsrhqpfb.supabase.co:5432/postgres
  const supabaseUrl = 'nehhbwuycrujvsrhqpfb.supabase.co';
  
  // 使用 Supabase 的连接字符串
  // 需要从 Supabase 获取正确的密码
  const connectionString = `postgres://postgres:${process.env.SUPABASE_SERVICE_KEY || 'your-service-key'}@${supabaseUrl}:5432/postgres`;
  
  // 尝试直接使用环境变量中的 URL
  const { Pool } = require('pg');
  
  const pool = new Pool({
    host: supabaseUrl,
    port: 5432,
    database: 'postgres',
    user: 'postgres',
    password: process.env.SUPABASE_SERVICE_KEY || 'your-service-key',
    ssl: { rejectUnauthorized: false }
  });

  try {
    console.log('正在连接 Supabase...');
    const client = await pool.connect();
    
    console.log('正在创建表...');
    await client.query(sql);
    
    console.log('✅ 表创建成功!');
    
    // 验证表
    const result = await client.query(`
      SELECT table_name FROM information_schema.tables 
      WHERE table_schema = 'public' 
      ORDER BY table_name;
    `);
    
    console.log('\n📋 已创建的表:');
    result.rows.forEach(row => {
      console.log(`  - ${row.table_name}`);
    });
    
    client.release();
    await pool.end();
  } catch (error) {
    console.error('❌ 创建表失败:', error.message);
    await pool.end();
    process.exit(1);
  }
}

createTables();
